package Utilities;

import java.util.HashMap;
import java.util.Map;

// Simple language switch and text lookup
public final class LanguageManager {

    // Current language (default English)
    private static String language = "en";

    // All translations: language (key to text)
    private static final Map<String, Map<String, String>> TEXT = new HashMap<>();

    // Initialize translation tables
    static {
        Map<String, String> en = new HashMap<>();
        en.put("app.title", "Patient Monitor");
        en.put("nav.home", "Home");
        en.put("nav.addPatient", "Add Patient");
        en.put("nav.account", "Account");
        en.put("nav.settings", "Settings");
        en.put("nav.logout", "Log Out");
        en.put("login.title", "Doctor Login");
        en.put("login.email", "Email");
        en.put("login.password", "Password");
        en.put("login.emailPlaceholder", "Enter your email");
        en.put("login.passwordPlaceholder", "Enter your password");
        en.put("login.signIn", "Sign In");
        en.put("login.demo", "Continue in Demo Mode");
        en.put("login.forgot", "Forgot Password?");
        en.put("login.register", "Register");
        en.put("login.missingDetails", "Please enter both email and password.");
        en.put("login.missingDetailsTitle", "Missing Login Details");
        en.put("login.failedTitle", "Login Failed");
        en.put("login.failedPrefix", "Login failed: ");
        en.put("login.resetUnavailable", "Password reset is not enabled in this local demo build. Please register a new test account or use Demo Mode.");
        en.put("login.resetTitle", "Password Reset");
        en.put("login.footer", "© 2025 HealthTrack. All Rights Reserved.");
        en.put("register.title", "Create Account");
        en.put("register.leftTitle", "Get Started");
        en.put("register.haveAccount", "Already have an account?");
        en.put("register.login", "Log in");
        en.put("register.email", "Email");
        en.put("register.password", "Password");
        en.put("register.givenName", "Given Name");
        en.put("register.familyName", "Family Name");
        en.put("register.emailPlaceholder", "Enter email");
        en.put("register.passwordPlaceholder", "At least 10 characters");
        en.put("register.givenPlaceholder", "Enter first name");
        en.put("register.familyPlaceholder", "Enter last name");
        en.put("register.terms", "I accept the terms of the agreement");
        en.put("register.signUp", "Sign up");
        en.put("register.acceptTerms", "You must accept the terms before continuing.");
        en.put("register.warning", "Warning");
        en.put("register.invalidEmail", "Please enter a valid email address.");
        en.put("register.invalidEmailTitle", "Invalid Email");
        en.put("register.missingName", "Please enter both given name and family name.");
        en.put("register.missingNameTitle", "Missing Name");
        en.put("register.invalidPassword", "Password must be at least 10 characters long.");
        en.put("register.invalidPasswordTitle", "Invalid Password");
        en.put("register.failedTitle", "Registration Failed");
        en.put("register.successMessage", "Registration successful. Please log in.");
        en.put("register.successTitle", "Success");
        en.put("register.failedPrefix", "Registration failed: ");
        en.put("home.loading", "Loading patients...");
        en.put("home.refresh", "Refresh");
        en.put("home.loadedSuffix", "patients loaded from server");
        en.put("home.offlineDemo", "Server unavailable, showing demo patients");
        en.put("add.title", "Add Patient");
        en.put("add.givenName", "Given Name");
        en.put("add.familyName", "Family Name");
        en.put("add.patientId", "Patient ID (optional)");
        en.put("add.gender", "Gender");
        en.put("add.age", "Age");
        en.put("add.bloodPressure", "Blood Pressure");
        en.put("add.givenPlaceholder", "Enter first name");
        en.put("add.familyPlaceholder", "Enter last name");
        en.put("add.idPlaceholder", "Leave empty (DB auto ID)");
        en.put("add.genderPlaceholder", "e.g. Female / Male / Other");
        en.put("add.agePlaceholder", "e.g. 32");
        en.put("add.bpPlaceholder", "e.g. 120/80");
        en.put("add.cancel", "Cancel");
        en.put("add.submit", "Add Patient");
        en.put("add.nameRequired", "Name cannot be empty");
        en.put("add.genderRequired", "Gender cannot be empty");
        en.put("add.invalidAge", "Please enter a valid numeric age");
        en.put("add.ageRange", "Age must be between 0 and 130");
        en.put("add.invalidBp", "Blood pressure should be like 120/80, with realistic systolic and diastolic values");
        en.put("add.success", "Patient added to database successfully");
        en.put("add.successTitle", "Success");
        en.put("add.failedPrefix", "Failed to add patient to database: ");
        en.put("add.inputError", "Input Error");
        en.put("account.title", "Doctor Account");
        en.put("account.subtitle", "Manage your account information, security settings, and preferences");
        en.put("account.changePhoto", "Change Photo");
        en.put("account.remove", "Remove");
        en.put("account.active", "Active");
        en.put("account.patientRecords", "Patient Records");
        en.put("account.fullName", "FULL NAME");
        en.put("account.emailAddress", "EMAIL ADDRESS");
        en.put("account.organization", "ORGANIZATION");
        en.put("account.role", "ROLE");
        en.put("account.fullNamePlaceholder", "Full name");
        en.put("account.emailPlaceholder", "Email address");
        en.put("account.organizationPlaceholder", "Organization");
        en.put("account.saveChanges", "Save Changes");
        en.put("account.metadata", "Account Metadata");
        en.put("account.userId", "USER ID");
        en.put("account.lastLogin", "LAST LOGIN");
        en.put("account.created", "ACCOUNT CREATED");
        en.put("account.daysAgo", "days ago");
        en.put("account.minutesAgo", "minutes ago");
        en.put("account.hoursAgo", "hours ago");
        en.put("account.profileSaved", "Profile saved.");
        en.put("account.chooseAvatar", "Choose an avatar image");
        en.put("account.avatarFailed", "Failed to set avatar: ");
        en.put("account.error", "Error");
        en.put("records.back", "← Back");
        en.put("records.importCsv", "Import CSV");
        en.put("records.deleteSelected", "Delete Selected");
        en.put("records.clearAll", "Clear All");
        en.put("records.search", "Search...");
        en.put("records.selectToDelete", "Please select a record to delete.");
        en.put("records.deleteQuestion", "Delete this record?");
        en.put("records.confirmDelete", "Confirm Delete");
        en.put("records.clearQuestion", "Are you sure you want to delete ALL records?");
        en.put("records.name", "Name");
        en.put("records.recordId", "Record ID");
        en.put("records.diagnosis", "Diagnosis");
        en.put("records.date", "Date");
        en.put("records.details", "Record Details");
        en.put("records.loading", "Loading records...");
        en.put("records.loadedFromServer", "records loaded from server");
        en.put("records.loadedFromLocal", "records loaded from local cache");
        en.put("records.loadFailed", "Could not load records");
        en.put("live.patient", "Patient");
        en.put("live.id", "ID");
        en.put("live.digitalTwin", "Digital Twin");
        en.put("live.exportPdf", "Print / Save PDF");
        en.put("live.exportJson", "Export Table (JSON)");
        en.put("live.last", "Last");
        en.put("live.hours", "hours");
        en.put("live.timeWindow", "Time Window (s):");
        en.put("live.apply", "Apply");
        en.put("live.invalidTimeWindowTitle", "Invalid Time Window");
        en.put("live.invalidTimeWindow", "Enter a time window from 5 to 300 seconds.");
        en.put("live.live", "LIVE");
        en.put("live.ecgWaveform", "ECG Waveform");
        en.put("live.respWaveform", "Respiratory Waveform");
        en.put("live.heartRate", "Heart Rate");
        en.put("live.spo2", "SpO2");
        en.put("live.respRate", "Resp Rate");
        en.put("live.bloodPressure", "Blood Pressure");
        en.put("live.breathsPerMin", "breaths / min");
        en.put("live.vitals", "Live Vitals");
        en.put("live.patientInfo", "Patient Info");
        en.put("live.hrShort", "HR");
        en.put("live.tempShort", "Temp");
        en.put("live.respShort", "Resp");
        en.put("live.bpShort", "BP");
        en.put("patient.gender", "Gender");
        en.put("patient.age", "Age");
        en.put("patient.discharge", "Discharge");
        en.put("patient.dischargePrompt", "Enter discharge note / diagnosis:");
        en.put("patient.dischargeTitle", "Discharge Patient");
        en.put("patient.dischargeFailedPrefix", "Discharge failed (DB not updated): ");
        en.put("patient.dischargeError", "Discharge Error");
        en.put("live.ecgAxis", "ECG (mV)");
        en.put("live.respAxis", "Resp (ΔZ)");
        en.put("digitalTwin.title", "Digital Twin");
        en.put("digitalTwin.nativeMode", "NATIVE VIEW");
        en.put("digitalTwin.noPatient", "No patient selected");
        en.put("digitalTwin.dashboardTitle", "Clinician Monitoring Dashboard");
        en.put("digitalTwin.subtitle", "Live telemetry from PatientServer DB • Notes are stored client-side only");
        en.put("digitalTwin.patientOverview", "Patient Overview");
        en.put("digitalTwin.healthRecords", "Health Records");
        en.put("digitalTwin.annotations", "Doctor Annotations");
        en.put("digitalTwin.trend", "Trend review");
        en.put("digitalTwin.medication", "Medication");
        en.put("digitalTwin.escalate", "Escalate");
        en.put("digitalTwin.trendNote", "Review vitals trend and reassess.");
        en.put("digitalTwin.medicationNote", "Medication review required.");
        en.put("digitalTwin.escalateNote", "Escalate for senior review.");
        en.put("digitalTwin.addNote", "Add Note");
        en.put("digitalTwin.liveTelemetry", "Live Telemetry");
        en.put("digitalTwin.ecg", "ECG");
        en.put("digitalTwin.respiration", "Respiration");
        en.put("digitalTwin.status", "Status");
        en.put("digitalTwin.stable", "Stable");
        en.put("digitalTwin.warning", "Warning");
        en.put("digitalTwin.critical", "Critical");
        en.put("digitalTwin.unknown", "Unknown");
        en.put("digitalTwin.noNotes", "No notes yet. Add a note to document observations.");
        en.put("digitalTwin.simBadge", "SIM: Java native dashboard");
        en.put("alerts.title", "Active Alerts");
        en.put("alerts.critical", "Critical");
        en.put("alerts.warnings", "Warnings");
        en.put("alerts.none", "No unacknowledged alerts.");
        en.put("alerts.criticalTag", "CRITICAL");
        en.put("alerts.warningTag", "WARNING");
        en.put("alerts.infoTag", "INFO");
        en.put("alerts.defaultHeadline", "Vitals out of range");
        en.put("alerts.patient", "Patient");
        en.put("alerts.viewPatient", "View Patient");
        en.put("alerts.acknowledge", "Acknowledge");
        en.put("alerts.notFound", "Patient not found (may have been discharged).");
        en.put("alerts.secondsAgo", "s ago");
        en.put("alerts.minutesAgo", "m ago");
        en.put("alerts.hoursAgo", "h ago");
        en.put("alerts.daysAgo", "d ago");
        en.put("alertCause.hrWarning", "Heart rate abnormal");
        en.put("alertCause.tempWarning", "Temperature abnormal");
        en.put("alertCause.bpWarning", "Blood pressure abnormal");
        en.put("alertCause.hrDanger", "Heart rate DANGER");
        en.put("alertCause.tempDanger", "Temperature DANGER");
        en.put("alertCause.bpDanger", "Blood pressure DANGER");
        en.put("alertCause.normal", "normal");
        en.put("alertCause.danger", "danger");
        en.put("alertCause.sysDiaDanger", "danger sys <90/>160 or dia <55/>110");
        en.put("live.history", "Vital History (Minute Averages)");
        en.put("live.sessionOnly", "Session-only vitals history; exports are saved locally.");
        en.put("live.col.time", "Time");
        en.put("live.col.hr", "HR (bpm)");
        en.put("live.col.resp", "Resp (/min)");
        en.put("live.col.temp", "Temp (°C)");
        en.put("live.col.spo2", "SpO2 (%)");
        en.put("export.noMinuteData", "No minute-averaged data available yet.\nPlease wait at least 1 full minute after monitoring starts.");
        en.put("export.vitalHistory", "Export Vital History");
        en.put("export.completeMessage", "Vital history exported successfully.");
        en.put("export.completeTitle", "Export Complete");
        en.put("export.failedMessage", "Failed to export vital history.");
        en.put("export.failedTitle", "Export Error");
        en.put("pdf.jobName", "Patient Vital Summary Report");
        en.put("pdf.summaryReport", "Summary Report");
        en.put("pdf.generated", "Generated");
        en.put("pdf.rangeLast", "Range: Last");
        en.put("pdf.overview", "Overview");
        en.put("pdf.overviewText", "This report summarizes the aggregated vital signs captured by the Patient Monitor client.");
        en.put("pdf.noData", "No data available for this time window.");
        en.put("pdf.vitalSummary", "Patient Vital Summary");
        en.put("pdf.patient", "Patient");
        en.put("pdf.respiratoryRate", "Respiratory Rate");
        en.put("pdf.temperature", "Temperature");
        en.put("pdf.footer", "Generated by Patient Monitor Client");
        en.put("pdf.mean", "Mean");
        en.put("pdf.min", "Min");
        en.put("pdf.max", "Max");
        en.put("settings.dangerTitle", "Danger zone");
        en.put("settings.dangerHint", "Permanently delete your account (cannot be undone)");
        en.put("settings.delete", "Delete account");
        en.put("settings.deleting", "Deleting...");
        en.put("settings.password", "Password");
        en.put("settings.title", "Settings");
        en.put("settings.darkMode", "Dark mode");
        en.put("settings.language", "Language");
        en.put("settings.reset", "Reset to defaults");
        en.put("settings.resetConfirmTitle", "Reset Settings");
        en.put("settings.resetConfirm", "Reset local preferences to defaults?");
        en.put("settings.logout", "Log out");
        en.put("settings.avatarTooltip", "Click to change profile picture");
        en.put("settings.removePhoto", "Remove photo");
        en.put("settings.choosePhoto", "Choose a profile picture");
        en.put("settings.imageFilter", "Images (png, jpg, jpeg)");
        en.put("settings.profilePhotoFailed", "Failed to set profile picture.");
        en.put("settings.error", "Error");
        en.put("settings.noAccount", "No logged-in account found.");
        en.put("settings.enterPassword", "Please enter your password to delete your account.");
        en.put("settings.confirmDeletePrompt", "This will permanently delete your account.\nType DELETE to confirm:");
        en.put("settings.confirmDeleteTitle", "Confirm deletion");
        en.put("settings.confirmMismatch", "Confirmation text did not match. Account was not deleted.");
        en.put("settings.noResponse", "Request failed (no response).");
        en.put("settings.accountDeleted", "Account deleted.");
        en.put("settings.deleteFailed", "Delete failed");
        en.put("settings.deleteFailedPrefix", "Delete failed: ");

        Map<String, String> zh = new HashMap<>();
        zh.put("app.title", "患者监测");
        zh.put("nav.home", "首页");
        zh.put("nav.addPatient", "添加患者");
        zh.put("nav.account", "账号");
        zh.put("nav.settings", "设置");
        zh.put("nav.logout", "退出登录");
        zh.put("login.title", "医生登录");
        zh.put("login.email", "邮箱");
        zh.put("login.password", "密码");
        zh.put("login.emailPlaceholder", "请输入邮箱");
        zh.put("login.passwordPlaceholder", "请输入密码");
        zh.put("login.signIn", "登录");
        zh.put("login.demo", "继续使用演示模式");
        zh.put("login.forgot", "忘记密码？");
        zh.put("login.register", "注册");
        zh.put("login.missingDetails", "请输入邮箱和密码。");
        zh.put("login.missingDetailsTitle", "登录信息缺失");
        zh.put("login.failedTitle", "登录失败");
        zh.put("login.failedPrefix", "登录失败：");
        zh.put("login.resetUnavailable", "本地演示版本未启用密码重置。请注册新的测试账号或使用演示模式。");
        zh.put("login.resetTitle", "密码重置");
        zh.put("login.footer", "© 2025 HealthTrack. 保留所有权利。");
        zh.put("register.title", "创建账号");
        zh.put("register.leftTitle", "开始使用");
        zh.put("register.haveAccount", "已经有账号？");
        zh.put("register.login", "登录");
        zh.put("register.email", "邮箱");
        zh.put("register.password", "密码");
        zh.put("register.givenName", "名");
        zh.put("register.familyName", "姓");
        zh.put("register.emailPlaceholder", "请输入邮箱");
        zh.put("register.passwordPlaceholder", "至少 10 个字符");
        zh.put("register.givenPlaceholder", "请输入名");
        zh.put("register.familyPlaceholder", "请输入姓");
        zh.put("register.terms", "我接受用户协议条款");
        zh.put("register.signUp", "注册");
        zh.put("register.acceptTerms", "继续前必须接受用户协议条款。");
        zh.put("register.warning", "警告");
        zh.put("register.invalidEmail", "请输入有效的邮箱地址。");
        zh.put("register.invalidEmailTitle", "邮箱无效");
        zh.put("register.missingName", "请输入名和姓。");
        zh.put("register.missingNameTitle", "姓名缺失");
        zh.put("register.invalidPassword", "密码长度至少为 10 个字符。");
        zh.put("register.invalidPasswordTitle", "密码无效");
        zh.put("register.failedTitle", "注册失败");
        zh.put("register.successMessage", "注册成功，请登录。");
        zh.put("register.successTitle", "成功");
        zh.put("register.failedPrefix", "注册失败：");
        zh.put("home.loading", "正在加载患者...");
        zh.put("home.refresh", "刷新");
        zh.put("home.loadedSuffix", "名患者已从服务器加载");
        zh.put("home.offlineDemo", "服务器不可用，正在显示演示患者");
        zh.put("add.title", "添加患者");
        zh.put("add.givenName", "名");
        zh.put("add.familyName", "姓");
        zh.put("add.patientId", "患者 ID（可选）");
        zh.put("add.gender", "性别");
        zh.put("add.age", "年龄");
        zh.put("add.bloodPressure", "血压");
        zh.put("add.givenPlaceholder", "请输入名");
        zh.put("add.familyPlaceholder", "请输入姓");
        zh.put("add.idPlaceholder", "留空（数据库自动生成 ID）");
        zh.put("add.genderPlaceholder", "例如 Female / Male / Other");
        zh.put("add.agePlaceholder", "例如 32");
        zh.put("add.bpPlaceholder", "例如 120/80");
        zh.put("add.cancel", "取消");
        zh.put("add.submit", "添加患者");
        zh.put("add.nameRequired", "姓名不能为空");
        zh.put("add.genderRequired", "性别不能为空");
        zh.put("add.invalidAge", "请输入有效的数字年龄");
        zh.put("add.ageRange", "年龄必须在 0 到 130 之间");
        zh.put("add.invalidBp", "血压格式应类似 120/80，且收缩压和舒张压数值需合理");
        zh.put("add.success", "患者已成功添加到数据库");
        zh.put("add.successTitle", "成功");
        zh.put("add.failedPrefix", "添加患者到数据库失败：");
        zh.put("add.inputError", "输入错误");
        zh.put("account.title", "医生账号");
        zh.put("account.subtitle", "管理账号信息、安全设置和偏好");
        zh.put("account.changePhoto", "更换照片");
        zh.put("account.remove", "移除");
        zh.put("account.active", "活跃");
        zh.put("account.patientRecords", "患者病历");
        zh.put("account.fullName", "姓名");
        zh.put("account.emailAddress", "邮箱地址");
        zh.put("account.organization", "机构");
        zh.put("account.role", "角色");
        zh.put("account.fullNamePlaceholder", "姓名");
        zh.put("account.emailPlaceholder", "邮箱地址");
        zh.put("account.organizationPlaceholder", "机构");
        zh.put("account.saveChanges", "保存修改");
        zh.put("account.metadata", "账号元数据");
        zh.put("account.userId", "用户 ID");
        zh.put("account.lastLogin", "上次登录");
        zh.put("account.created", "账号创建时间");
        zh.put("account.daysAgo", "天前");
        zh.put("account.minutesAgo", "分钟前");
        zh.put("account.hoursAgo", "小时前");
        zh.put("account.profileSaved", "资料已保存。");
        zh.put("account.chooseAvatar", "选择头像图片");
        zh.put("account.avatarFailed", "设置头像失败：");
        zh.put("account.error", "错误");
        zh.put("records.back", "← 返回");
        zh.put("records.importCsv", "导入 CSV");
        zh.put("records.deleteSelected", "删除选中");
        zh.put("records.clearAll", "清空全部");
        zh.put("records.search", "搜索...");
        zh.put("records.selectToDelete", "请选择要删除的病历。");
        zh.put("records.deleteQuestion", "确定删除这条病历？");
        zh.put("records.confirmDelete", "确认删除");
        zh.put("records.clearQuestion", "确定要删除全部病历吗？");
        zh.put("records.name", "姓名");
        zh.put("records.recordId", "病历 ID");
        zh.put("records.diagnosis", "诊断");
        zh.put("records.date", "日期");
        zh.put("records.details", "病历详情");
        zh.put("records.loading", "正在加载病历...");
        zh.put("records.loadedFromServer", "条病历已从服务器加载");
        zh.put("records.loadedFromLocal", "条病历已从本地缓存加载");
        zh.put("records.loadFailed", "无法加载病历");
        zh.put("live.patient", "患者");
        zh.put("live.id", "ID");
        zh.put("live.digitalTwin", "数字孪生");
        zh.put("live.exportPdf", "打印 / 另存 PDF");
        zh.put("live.exportJson", "导出表格 (JSON)");
        zh.put("live.last", "最近");
        zh.put("live.hours", "小时");
        zh.put("live.timeWindow", "时间窗口（秒）：");
        zh.put("live.apply", "应用");
        zh.put("live.invalidTimeWindowTitle", "时间窗口无效");
        zh.put("live.invalidTimeWindow", "请输入 5 到 300 秒之间的时间窗口。");
        zh.put("live.live", "实时");
        zh.put("live.ecgWaveform", "心电波形");
        zh.put("live.respWaveform", "呼吸波形");
        zh.put("live.heartRate", "心率");
        zh.put("live.spo2", "血氧");
        zh.put("live.respRate", "呼吸频率");
        zh.put("live.bloodPressure", "血压");
        zh.put("live.breathsPerMin", "次 / 分钟");
        zh.put("live.vitals", "实时生命体征");
        zh.put("live.patientInfo", "患者信息");
        zh.put("live.hrShort", "心率");
        zh.put("live.tempShort", "体温");
        zh.put("live.respShort", "呼吸");
        zh.put("live.bpShort", "血压");
        zh.put("patient.gender", "性别");
        zh.put("patient.age", "年龄");
        zh.put("patient.discharge", "出院");
        zh.put("patient.dischargePrompt", "请输入出院备注 / 诊断：");
        zh.put("patient.dischargeTitle", "患者出院");
        zh.put("patient.dischargeFailedPrefix", "出院失败（数据库未更新）：");
        zh.put("patient.dischargeError", "出院错误");
        zh.put("live.ecgAxis", "心电 (mV)");
        zh.put("live.respAxis", "呼吸 (ΔZ)");
        zh.put("digitalTwin.title", "数字孪生");
        zh.put("digitalTwin.nativeMode", "原生视图");
        zh.put("digitalTwin.noPatient", "未选择患者");
        zh.put("digitalTwin.dashboardTitle", "临床监测仪表盘");
        zh.put("digitalTwin.subtitle", "来自 PatientServer DB 的实时遥测 • 备注仅存储在客户端");
        zh.put("digitalTwin.patientOverview", "患者概览");
        zh.put("digitalTwin.healthRecords", "健康记录");
        zh.put("digitalTwin.annotations", "医生备注");
        zh.put("digitalTwin.trend", "趋势复查");
        zh.put("digitalTwin.medication", "用药");
        zh.put("digitalTwin.escalate", "升级处理");
        zh.put("digitalTwin.trendNote", "复查生命体征趋势并重新评估。");
        zh.put("digitalTwin.medicationNote", "需要进行用药复查。");
        zh.put("digitalTwin.escalateNote", "升级给上级医生复查。");
        zh.put("digitalTwin.addNote", "添加备注");
        zh.put("digitalTwin.liveTelemetry", "实时遥测");
        zh.put("digitalTwin.ecg", "心电");
        zh.put("digitalTwin.respiration", "呼吸");
        zh.put("digitalTwin.status", "状态");
        zh.put("digitalTwin.stable", "稳定");
        zh.put("digitalTwin.warning", "警告");
        zh.put("digitalTwin.critical", "严重");
        zh.put("digitalTwin.unknown", "未知");
        zh.put("digitalTwin.noNotes", "暂无备注。添加备注以记录观察。");
        zh.put("digitalTwin.simBadge", "SIM：Java 原生仪表盘");
        zh.put("alerts.title", "活动警报");
        zh.put("alerts.critical", "严重");
        zh.put("alerts.warnings", "警告");
        zh.put("alerts.none", "没有未确认的警报。");
        zh.put("alerts.criticalTag", "严重");
        zh.put("alerts.warningTag", "警告");
        zh.put("alerts.infoTag", "信息");
        zh.put("alerts.defaultHeadline", "生命体征超出范围");
        zh.put("alerts.patient", "患者");
        zh.put("alerts.viewPatient", "查看患者");
        zh.put("alerts.acknowledge", "确认");
        zh.put("alerts.notFound", "未找到患者（可能已出院）。");
        zh.put("alerts.secondsAgo", "秒前");
        zh.put("alerts.minutesAgo", "分钟前");
        zh.put("alerts.hoursAgo", "小时前");
        zh.put("alerts.daysAgo", "天前");
        zh.put("alertCause.hrWarning", "心率异常");
        zh.put("alertCause.tempWarning", "体温异常");
        zh.put("alertCause.bpWarning", "血压异常");
        zh.put("alertCause.hrDanger", "心率危险");
        zh.put("alertCause.tempDanger", "体温危险");
        zh.put("alertCause.bpDanger", "血压危险");
        zh.put("alertCause.normal", "正常范围");
        zh.put("alertCause.danger", "危险范围");
        zh.put("alertCause.sysDiaDanger", "危险范围：收缩压 <90/>160 或舒张压 <55/>110");
        zh.put("live.history", "生命体征历史（分钟平均）");
        zh.put("live.sessionOnly", "生命体征历史仅保存在本次会话中；导出文件保存在本地。");
        zh.put("live.col.time", "时间");
        zh.put("live.col.hr", "心率 (bpm)");
        zh.put("live.col.resp", "呼吸 (/min)");
        zh.put("live.col.temp", "体温 (°C)");
        zh.put("live.col.spo2", "血氧 (%)");
        zh.put("export.noMinuteData", "还没有分钟平均数据。\n请在监测开始后至少等待 1 分钟。");
        zh.put("export.vitalHistory", "导出生命体征历史");
        zh.put("export.completeMessage", "生命体征历史已成功导出。");
        zh.put("export.completeTitle", "导出完成");
        zh.put("export.failedMessage", "导出生命体征历史失败。");
        zh.put("export.failedTitle", "导出错误");
        zh.put("pdf.jobName", "患者生命体征摘要报告");
        zh.put("pdf.summaryReport", "摘要报告");
        zh.put("pdf.generated", "生成时间");
        zh.put("pdf.rangeLast", "范围：最近");
        zh.put("pdf.overview", "概览");
        zh.put("pdf.overviewText", "本报告汇总了 Patient Monitor 客户端采集的生命体征聚合数据。");
        zh.put("pdf.noData", "该时间窗口内没有可用数据。");
        zh.put("pdf.vitalSummary", "患者生命体征摘要");
        zh.put("pdf.patient", "患者");
        zh.put("pdf.respiratoryRate", "呼吸频率");
        zh.put("pdf.temperature", "体温");
        zh.put("pdf.footer", "由 Patient Monitor Client 生成");
        zh.put("pdf.mean", "平均值");
        zh.put("pdf.min", "最小值");
        zh.put("pdf.max", "最大值");
        zh.put("settings.dangerTitle", "危险区域");
        zh.put("settings.dangerHint", "永久删除账号（此操作无法撤销）");
        zh.put("settings.delete", "删除账号");
        zh.put("settings.deleting", "正在删除...");
        zh.put("settings.password", "密码");
        zh.put("settings.title", "设置");
        zh.put("settings.darkMode", "深色模式");
        zh.put("settings.language", "语言");
        zh.put("settings.reset", "恢复默认");
        zh.put("settings.resetConfirmTitle", "重置设置");
        zh.put("settings.resetConfirm", "确定要将本地偏好恢复为默认设置吗？");
        zh.put("settings.logout", "退出登录");
        zh.put("settings.avatarTooltip", "点击更换头像");
        zh.put("settings.removePhoto", "移除照片");
        zh.put("settings.choosePhoto", "选择头像图片");
        zh.put("settings.imageFilter", "图片（png、jpg、jpeg）");
        zh.put("settings.profilePhotoFailed", "设置头像失败。");
        zh.put("settings.error", "错误");
        zh.put("settings.noAccount", "未找到已登录账号。");
        zh.put("settings.enterPassword", "请输入密码以删除账号。");
        zh.put("settings.confirmDeletePrompt", "此操作将永久删除你的账号。\n请输入 DELETE 确认：");
        zh.put("settings.confirmDeleteTitle", "确认删除");
        zh.put("settings.confirmMismatch", "确认文本不匹配，账号未删除。");
        zh.put("settings.noResponse", "请求失败（没有响应）。");
        zh.put("settings.accountDeleted", "账号已删除。");
        zh.put("settings.deleteFailed", "删除失败");
        zh.put("settings.deleteFailedPrefix", "删除失败：");

        TEXT.put("en", en);
        TEXT.put("zh", zh);
    }

    // Utility class (no instances)
    private LanguageManager() {}

    // Change current language
    public static void setLanguage(String lang) {
        if (lang == null) lang = "en";
        lang = lang.trim().toLowerCase();
        language = TEXT.containsKey(lang) ? lang : "en";
    }

    // Get current language
    public static String getLanguage() {
        return language;
    }

    // Translate key based on the current language
    public static String t(String key) {
        Map<String, String> table = TEXT.getOrDefault(language, TEXT.get("en"));
        return table.getOrDefault(key, key);
    }
}
